### ISSUE TITLE
About Training & evaluation code

### ISSUE THREAD

**Issue by Jemmagu** [hangg7/deformable-kernels#2]
Hi @hangg7 ,
Thanks for your great work.
I'm curious when will you release the Training & evaluation code

Thanks a lot.

**Comment by hangg7** [comment]
Hi, Thanks for your interest in our work! I am currently working on something else, but will try uploading the classification code during the summer. Thanks!

**Comment by smandal94** [comment]
@hangg7 I'm interested in trying out the classification code. If you're looking out to releasing the training and evaluation code, it would be really helpful. Thanks!
