### ISSUE TITLE
Unable to run DeformConv2d

### ISSUE THREAD

**Issue by vkothapally** [hangg7/deformable-kernels#3]
I couldn't get `pip install -e .` command to run. I have installed using `python setup.py install` instead. I'm not sure if this is the reason for all the issues. Anyways, I tried to import and test just DeformConv2d and got this error. It would be a great help if you can help me out.

Test.py:
```python
from deformable_kernels.modules import DeformConv2d
model = DeformConv2d(in_planes=1,
			         out_planes=64,
			         kernel_size=5,
			         stride=2,
			         padding=2,
			         dilation=0,
			         bias=True)
```

Output:
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from deformable_kernels.modules import DeformConv2d
  File "/data/scratch/vkk160330/Projects/pytorch/IEEE_Final/deformable-kernels/deformable_kernels/modules/__init__.py", line 11, in <module>
    from .deform_conv import DeformConv2d
  File "/data/scratch/vkk160330/Projects/pytorch/IEEE_Final/deformable-kernels/deformable_kernels/modules/deform_conv.py", line 10, in <module>
    from .deform_kernel import DeformKernelConv2d
  File "/data/scratch/vkk160330/Projects/pytorch/IEEE_Final/deformable-kernels/deformable_kernels/modules/deform_kernel.py", line 14, in <module>
    from ..ops.deform_kernel.functions import nd_linear_sample
  File "/data/scratch/vkk160330/Projects/pytorch/IEEE_Final/deformable-kernels/deformable_kernels/ops/deform_kernel/functions/__init__.py", line 10, in <module>
    from .filter_sample_depthwise import (
  File "/data/scratch/vkk160330/Projects/pytorch/IEEE_Final/deformable-kernels/deformable_kernels/ops/deform_kernel/functions/filter_sample_depthwise.py", line 14, in <module>
    from .. import filter_sample_depthwise_cuda
ImportError: cannot import name 'filter_sample_depthwise_cuda'
```

**Comment by hangg7** [comment]
Hi, according to your trace log, it seems you have your installation compromised:
```
File "/data/scratch/vkk160330/Projects/pytorch/IEEE_Final/deformable-kernels/deformable_kernels/ops/deform_kernel/functions/filter_sample_depthwise.py", line 14, in <module>
    from .. import filter_sample_depthwise_cuda
```

This specific [line](https://github.com/hangg7/deformable-kernels/blob/886c35389ab9fb96b36d2ab89c56186381acff32/deformable_kernels/ops/deform_kernel/functions/filter_sample_depthwise.py#L14) needs to import the cuda extension that was meant to be built in the `deformable-kernels/deformable_kernels/ops/deform_kernel/functions` directory. I would suggest to check if `filter_sample_depthwise_cuda.*.so` exists at such directory at the first place.

By running `python setup.py install` you will not build any cuda extension, and that should be the culprit. Instead, you should try `python setup.py develop` as it is basically the `setup.py` [equivalent](https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop) of the pip command we specified.

**Comment by hangg7** [comment]
Hi, according to your trace log, it seems you have your installation compromised:
```
File "/data/scratch/vkk160330/Projects/pytorch/IEEE_Final/deformable-kernels/deformable_kernels/ops/deform_kernel/functions/filter_sample_depthwise.py", line 14, in <module>
    from .. import filter_sample_depthwise_cuda
```

This specific [line](https://github.com/hangg7/deformable-kernels/blob/886c35389ab9fb96b36d2ab89c56186381acff32/deformable_kernels/ops/deform_kernel/functions/filter_sample_depthwise.py#L14) needs to import the cuda extension that was meant to be built in the `deformable-kernels/deformable_kernels/ops/deform_kernel/functions` directory. I would suggest to check if `filter_sample_depthwise_cuda.*.so` exists at such directory at the first place.

By running `python setup.py install` you will not build any cuda extension, and that should be the culprit. Instead, you should try `python setup.py develop` as it is basically the `setup.py` [equivalent](https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop) of the pip command we specified.

I'd suggest try solving pip install issue first, which is very likely related to your local CUDA setup and not related to this specific project. Therefore I'm closing this, feel free to reopen it if otherwise.

PS: please include your snippets and error logs using markdown format, it was not as readable otherwise. Thanks!

**Comment by vkothapally** [comment]
Hi Hang Gao, Thanks for your reply. I was able to import the module after using `python setup.py build`. I was able to locate `filter_sample_depthwise_cuda.*.so` in `deformable_kernels/ops/deform_kernel` folder. However, I have encountered an issue while backpropagating the gradients from loss.

# Testing DeformConv2d:
``` python
import torch
import torch.nn as nn
from deformable_kernels.modules import DeformConv2d

criterion = nn.MSELoss()
dcn = DeformConv2d(in_planes=1,
        out_planes=1,
        kernel_size=5,
        padding=2,
        stride=1,
        dilation=1,
        groups=1,
        bias=False,
        offset_clip=None,
    ).to('cuda')
x = torch.randn(1,1,256,256).to('cuda')
y = torch.randn(1,1,256,256).to('cuda')
estimate = dcn(x)
loss = criterion(estimate, y)
loss.backward()
```

# Output:
```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    loss.backward()
  File "/data/scratch/vkk160330/anaconda3/envs/deformable/lib/python3.6/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/scratch/vkk160330/anaconda3/envs/deformable/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: function DeformableSampleDepthwiseFunctionBackward returned an incorrect number of gradients (expected 9, got 8)
```

**Comment by Magauiya** [comment]
@

> Hi Hang Gao, Thanks for your reply. I was able to import the module after using `python setup.py build`. I was able to locate `filter_sample_depthwise_cuda.*.so` in `deformable_kernels/ops/deform_kernel` folder. However, I have encountered an issue while backpropagating the gradients from loss.
> 
> # Testing DeformConv2d:
> ```python
> import torch
> import torch.nn as nn
> from deformable_kernels.modules import DeformConv2d
> 
> criterion = nn.MSELoss()
> dcn = DeformConv2d(in_planes=1,
>         out_planes=1,
>         kernel_size=5,
>         padding=2,
>         stride=1,
>         dilation=1,
>         groups=1,
>         bias=False,
>         offset_clip=None,
>     ).to('cuda')
> x = torch.randn(1,1,256,256).to('cuda')
> y = torch.randn(1,1,256,256).to('cuda')
> estimate = dcn(x)
> loss = criterion(estimate, y)
> loss.backward()
> ```
> 
> # Output:
> ```
> Traceback (most recent call last):
>   File "test.py", line 29, in <module>
>     loss.backward()
>   File "/data/scratch/vkk160330/anaconda3/envs/deformable/lib/python3.6/site-packages/torch/tensor.py", line 166, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/data/scratch/vkk160330/anaconda3/envs/deformable/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: function DeformableSampleDepthwiseFunctionBackward returned an incorrect number of gradients (expected 9, got 8)
> ```

Have you solved the issue?

**Comment by Magauiya** [comment]
> Hi Hang Gao, Thanks for your reply. I was able to import the module after using `python setup.py build`. I was able to locate `filter_sample_depthwise_cuda.*.so` in `deformable_kernels/ops/deform_kernel` folder. However, I have encountered an issue while backpropagating the gradients from loss.
> 
> # Testing DeformConv2d:
> ```python
> import torch
> import torch.nn as nn
> from deformable_kernels.modules import DeformConv2d
> 
> criterion = nn.MSELoss()
> dcn = DeformConv2d(in_planes=1,
>         out_planes=1,
>         kernel_size=5,
>         padding=2,
>         stride=1,
>         dilation=1,
>         groups=1,
>         bias=False,
>         offset_clip=None,
>     ).to('cuda')
> x = torch.randn(1,1,256,256).to('cuda')
> y = torch.randn(1,1,256,256).to('cuda')
> estimate = dcn(x)
> loss = criterion(estimate, y)
> loss.backward()
> ```
> 
> # Output:
> ```
> Traceback (most recent call last):
>   File "test.py", line 29, in <module>
>     loss.backward()
>   File "/data/scratch/vkk160330/anaconda3/envs/deformable/lib/python3.6/site-packages/torch/tensor.py", line 166, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/data/scratch/vkk160330/anaconda3/envs/deformable/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: function DeformableSampleDepthwiseFunctionBackward returned an incorrect number of gradients (expected 9, got 8)
> ```

Go to the filesampledepthwise.py in **functions** folder and change return tuple to be one more None. This should work)
